#!/bin/sh

inc_prefix=
lib_prefix=
bin_prefix=
exec_prefix_set=no

usage="\
Usage: yars-config [--exec] [--lib-prefix] [--bin-prefix] [--inc-prefix] [--version] [--cflags] [--libs]"

if test $# -eq 0; then
      echo "${usage}" 1>&2
      exit 1
fi

while test $# -gt 0; do
  case "$1" in
  -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
  *) optarg= ;;
  esac

  case $1 in
    --inc-prefix)
      echo $prefix
      ;;
    --version)
      echo @VERSION@
      ;;
    --lib-prefix)
      echo  @LIB_PREFIX@
      ;;
    --bin-prefix)
      echo  @BIN_PREFIX@
      ;;
    --exec)
      echo  @BIN_PREFIX@/@YARS_TARGET@
      ;;
    --inc-prefix)
      echo  @INC_PREFIX@
      ;;
    --cflags)
      echo  -I@INC_PREFIX@
      ;;
    --libs)
      echo  -L@LIB_PREFIX@ -lYarsRobotController
      ;;
    *)
      echo "${usage}" 1>&2
      exit 1
      ;;
  esac
  shift
done
