# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Volumes/Eregion/projects/yars

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Volumes/Eregion/projects/yars

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool..."
	/opt/homebrew/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool for source..."
	/opt/homebrew/bin/cpack --config ./CPackSourceConfig.cmake /Volumes/Eregion/projects/yars/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Volumes/Eregion/projects/yars/CMakeFiles /Volumes/Eregion/projects/yars//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Volumes/Eregion/projects/yars/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uninstall.dir/build.make CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named yars

# Build rule for target.
yars: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yars
.PHONY : yars

# fast build rule for target.
yars/fast:
	$(MAKE) $(MAKESILENT) -f src/yars/CMakeFiles/yars.dir/build.make src/yars/CMakeFiles/yars.dir/build
.PHONY : yars/fast

#=============================================================================
# Target rules for targets named YarsDataTypes

# Build rule for target.
YarsDataTypes: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 YarsDataTypes
.PHONY : YarsDataTypes

# fast build rule for target.
YarsDataTypes/fast:
	$(MAKE) $(MAKESILENT) -f src/yars/types/CMakeFiles/YarsDataTypes.dir/build.make src/yars/types/CMakeFiles/YarsDataTypes.dir/build
.PHONY : YarsDataTypes/fast

#=============================================================================
# Target rules for targets named YarsConfiguration

# Build rule for target.
YarsConfiguration: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 YarsConfiguration
.PHONY : YarsConfiguration

# fast build rule for target.
YarsConfiguration/fast:
	$(MAKE) $(MAKESILENT) -f src/yars/configuration/CMakeFiles/YarsConfiguration.dir/build.make src/yars/configuration/CMakeFiles/YarsConfiguration.dir/build
.PHONY : YarsConfiguration/fast

#=============================================================================
# Target rules for targets named YarsViewConsole

# Build rule for target.
YarsViewConsole: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 YarsViewConsole
.PHONY : YarsViewConsole

# fast build rule for target.
YarsViewConsole/fast:
	$(MAKE) $(MAKESILENT) -f src/yars/view/console/CMakeFiles/YarsViewConsole.dir/build.make src/yars/view/console/CMakeFiles/YarsViewConsole.dir/build
.PHONY : YarsViewConsole/fast

#=============================================================================
# Target rules for targets named YarsPhysics

# Build rule for target.
YarsPhysics: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 YarsPhysics
.PHONY : YarsPhysics

# fast build rule for target.
YarsPhysics/fast:
	$(MAKE) $(MAKESILENT) -f src/yars/physics/CMakeFiles/YarsPhysics.dir/build.make src/yars/physics/CMakeFiles/YarsPhysics.dir/build
.PHONY : YarsPhysics/fast

#=============================================================================
# Target rules for targets named YarsUtil

# Build rule for target.
YarsUtil: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 YarsUtil
.PHONY : YarsUtil

# fast build rule for target.
YarsUtil/fast:
	$(MAKE) $(MAKESILENT) -f src/yars/util/CMakeFiles/YarsUtil.dir/build.make src/yars/util/CMakeFiles/YarsUtil.dir/build
.PHONY : YarsUtil/fast

#=============================================================================
# Target rules for targets named YarsMain

# Build rule for target.
YarsMain: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 YarsMain
.PHONY : YarsMain

# fast build rule for target.
YarsMain/fast:
	$(MAKE) $(MAKESILENT) -f src/yars/main/CMakeFiles/YarsMain.dir/build.make src/yars/main/CMakeFiles/YarsMain.dir/build
.PHONY : YarsMain/fast

#=============================================================================
# Target rules for targets named YarsLogging

# Build rule for target.
YarsLogging: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 YarsLogging
.PHONY : YarsLogging

# fast build rule for target.
YarsLogging/fast:
	$(MAKE) $(MAKESILENT) -f src/yars/logging/CMakeFiles/YarsLogging.dir/build.make src/yars/logging/CMakeFiles/YarsLogging.dir/build
.PHONY : YarsLogging/fast

#=============================================================================
# Target rules for targets named YarsRobotController

# Build rule for target.
YarsRobotController: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 YarsRobotController
.PHONY : YarsRobotController

# fast build rule for target.
YarsRobotController/fast:
	$(MAKE) $(MAKESILENT) -f src/yars/rc/CMakeFiles/YarsRobotController.dir/build.make src/yars/rc/CMakeFiles/YarsRobotController.dir/build
.PHONY : YarsRobotController/fast

#=============================================================================
# Target rules for targets named braitenberg-tcpip

# Build rule for target.
braitenberg-tcpip: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 braitenberg-tcpip
.PHONY : braitenberg-tcpip

# fast build rule for target.
braitenberg-tcpip/fast:
	$(MAKE) $(MAKESILENT) -f contrib/braitenbergCom/CMakeFiles/braitenberg-tcpip.dir/build.make contrib/braitenbergCom/CMakeFiles/braitenberg-tcpip.dir/build
.PHONY : braitenberg-tcpip/fast

#=============================================================================
# Target rules for targets named braitenberg-pipe

# Build rule for target.
braitenberg-pipe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 braitenberg-pipe
.PHONY : braitenberg-pipe

# fast build rule for target.
braitenberg-pipe/fast:
	$(MAKE) $(MAKESILENT) -f contrib/braitenbergPipe/CMakeFiles/braitenberg-pipe.dir/build.make contrib/braitenbergPipe/CMakeFiles/braitenberg-pipe.dir/build
.PHONY : braitenberg-pipe/fast

#=============================================================================
# Target rules for targets named YarsNamedPipeCom

# Build rule for target.
YarsNamedPipeCom: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 YarsNamedPipeCom
.PHONY : YarsNamedPipeCom

# fast build rule for target.
YarsNamedPipeCom/fast:
	$(MAKE) $(MAKESILENT) -f contrib/namedPipeClientCom/CMakeFiles/YarsNamedPipeCom.dir/build.make contrib/namedPipeClientCom/CMakeFiles/YarsNamedPipeCom.dir/build
.PHONY : YarsNamedPipeCom/fast

#=============================================================================
# Target rules for targets named YarsClientCom

# Build rule for target.
YarsClientCom: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 YarsClientCom
.PHONY : YarsClientCom

# fast build rule for target.
YarsClientCom/fast:
	$(MAKE) $(MAKESILENT) -f contrib/cppClientCom/CMakeFiles/YarsClientCom.dir/build.make contrib/cppClientCom/CMakeFiles/YarsClientCom.dir/build
.PHONY : YarsClientCom/fast

#=============================================================================
# Target rules for targets named YarsControllerNIL

# Build rule for target.
YarsControllerNIL: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 YarsControllerNIL
.PHONY : YarsControllerNIL

# fast build rule for target.
YarsControllerNIL/fast:
	$(MAKE) $(MAKESILENT) -f contrib/controller/CMakeFiles/YarsControllerNIL.dir/build.make contrib/controller/CMakeFiles/YarsControllerNIL.dir/build
.PHONY : YarsControllerNIL/fast

#=============================================================================
# Target rules for targets named YarsControllerSine

# Build rule for target.
YarsControllerSine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 YarsControllerSine
.PHONY : YarsControllerSine

# fast build rule for target.
YarsControllerSine/fast:
	$(MAKE) $(MAKESILENT) -f contrib/controller/CMakeFiles/YarsControllerSine.dir/build.make contrib/controller/CMakeFiles/YarsControllerSine.dir/build
.PHONY : YarsControllerSine/fast

#=============================================================================
# Target rules for targets named YarsControllerSquareWave

# Build rule for target.
YarsControllerSquareWave: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 YarsControllerSquareWave
.PHONY : YarsControllerSquareWave

# fast build rule for target.
YarsControllerSquareWave/fast:
	$(MAKE) $(MAKESILENT) -f contrib/controller/CMakeFiles/YarsControllerSquareWave.dir/build.make contrib/controller/CMakeFiles/YarsControllerSquareWave.dir/build
.PHONY : YarsControllerSquareWave/fast

#=============================================================================
# Target rules for targets named YarsControllerBraitenberg2b

# Build rule for target.
YarsControllerBraitenberg2b: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 YarsControllerBraitenberg2b
.PHONY : YarsControllerBraitenberg2b

# fast build rule for target.
YarsControllerBraitenberg2b/fast:
	$(MAKE) $(MAKESILENT) -f contrib/controller/CMakeFiles/YarsControllerBraitenberg2b.dir/build.make contrib/controller/CMakeFiles/YarsControllerBraitenberg2b.dir/build
.PHONY : YarsControllerBraitenberg2b/fast

#=============================================================================
# Target rules for targets named YarsControllerBraitenberg2a

# Build rule for target.
YarsControllerBraitenberg2a: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 YarsControllerBraitenberg2a
.PHONY : YarsControllerBraitenberg2a

# fast build rule for target.
YarsControllerBraitenberg2a/fast:
	$(MAKE) $(MAKESILENT) -f contrib/controller/CMakeFiles/YarsControllerBraitenberg2a.dir/build.make contrib/controller/CMakeFiles/YarsControllerBraitenberg2a.dir/build
.PHONY : YarsControllerBraitenberg2a/fast

#=============================================================================
# Target rules for targets named YarsControllerBraitenberg3b

# Build rule for target.
YarsControllerBraitenberg3b: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 YarsControllerBraitenberg3b
.PHONY : YarsControllerBraitenberg3b

# fast build rule for target.
YarsControllerBraitenberg3b/fast:
	$(MAKE) $(MAKESILENT) -f contrib/controller/CMakeFiles/YarsControllerBraitenberg3b.dir/build.make contrib/controller/CMakeFiles/YarsControllerBraitenberg3b.dir/build
.PHONY : YarsControllerBraitenberg3b/fast

#=============================================================================
# Target rules for targets named YarsControllerBraitenberg3a

# Build rule for target.
YarsControllerBraitenberg3a: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 YarsControllerBraitenberg3a
.PHONY : YarsControllerBraitenberg3a

# fast build rule for target.
YarsControllerBraitenberg3a/fast:
	$(MAKE) $(MAKESILENT) -f contrib/controller/CMakeFiles/YarsControllerBraitenberg3a.dir/build.make contrib/controller/CMakeFiles/YarsControllerBraitenberg3a.dir/build
.PHONY : YarsControllerBraitenberg3a/fast

#=============================================================================
# Target rules for targets named YarsControllerHexapod

# Build rule for target.
YarsControllerHexapod: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 YarsControllerHexapod
.PHONY : YarsControllerHexapod

# fast build rule for target.
YarsControllerHexapod/fast:
	$(MAKE) $(MAKESILENT) -f contrib/controller/CMakeFiles/YarsControllerHexapod.dir/build.make contrib/controller/CMakeFiles/YarsControllerHexapod.dir/build
.PHONY : YarsControllerHexapod/fast

#=============================================================================
# Target rules for targets named YarsControllerConstantValue

# Build rule for target.
YarsControllerConstantValue: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 YarsControllerConstantValue
.PHONY : YarsControllerConstantValue

# fast build rule for target.
YarsControllerConstantValue/fast:
	$(MAKE) $(MAKESILENT) -f contrib/controller/CMakeFiles/YarsControllerConstantValue.dir/build.make contrib/controller/CMakeFiles/YarsControllerConstantValue.dir/build
.PHONY : YarsControllerConstantValue/fast

#=============================================================================
# Target rules for targets named YarsControllerNamedPipe

# Build rule for target.
YarsControllerNamedPipe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 YarsControllerNamedPipe
.PHONY : YarsControllerNamedPipe

# fast build rule for target.
YarsControllerNamedPipe/fast:
	$(MAKE) $(MAKESILENT) -f contrib/controller/CMakeFiles/YarsControllerNamedPipe.dir/build.make contrib/controller/CMakeFiles/YarsControllerNamedPipe.dir/build
.PHONY : YarsControllerNamedPipe/fast

#=============================================================================
# Target rules for targets named YarsControllerTCPIP

# Build rule for target.
YarsControllerTCPIP: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 YarsControllerTCPIP
.PHONY : YarsControllerTCPIP

# fast build rule for target.
YarsControllerTCPIP/fast:
	$(MAKE) $(MAKESILENT) -f contrib/controller/CMakeFiles/YarsControllerTCPIP.dir/build.make contrib/controller/CMakeFiles/YarsControllerTCPIP.dir/build
.PHONY : YarsControllerTCPIP/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... uninstall"
	@echo "... YarsClientCom"
	@echo "... YarsConfiguration"
	@echo "... YarsControllerBraitenberg2a"
	@echo "... YarsControllerBraitenberg2b"
	@echo "... YarsControllerBraitenberg3a"
	@echo "... YarsControllerBraitenberg3b"
	@echo "... YarsControllerConstantValue"
	@echo "... YarsControllerHexapod"
	@echo "... YarsControllerNIL"
	@echo "... YarsControllerNamedPipe"
	@echo "... YarsControllerSine"
	@echo "... YarsControllerSquareWave"
	@echo "... YarsControllerTCPIP"
	@echo "... YarsDataTypes"
	@echo "... YarsLogging"
	@echo "... YarsMain"
	@echo "... YarsNamedPipeCom"
	@echo "... YarsPhysics"
	@echo "... YarsRobotController"
	@echo "... YarsUtil"
	@echo "... YarsViewConsole"
	@echo "... braitenberg-pipe"
	@echo "... braitenberg-tcpip"
	@echo "... yars"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

