if(EXISTS "/Volumes/Eregion/projects/yars/tests/yars_tests[1]_tests.cmake")
  include("/Volumes/Eregion/projects/yars/tests/yars_tests[1]_tests.cmake")
else()
  add_test(yars_tests_NOT_BUILT yars_tests_NOT_BUILT)
endif()
