add_test([=[P3DTest.DefaultConstructor]=]  /Volumes/Eregion/projects/yars/bin/yars_tests [==[--gtest_filter=P3DTest.DefaultConstructor]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[P3DTest.DefaultConstructor]=]  PROPERTIES WORKING_DIRECTORY /Volumes/Eregion/projects/yars/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[P3DTest.ParameterizedConstructor]=]  /Volumes/Eregion/projects/yars/bin/yars_tests [==[--gtest_filter=P3DTest.ParameterizedConstructor]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[P3DTest.ParameterizedConstructor]=]  PROPERTIES WORKING_DIRECTORY /Volumes/Eregion/projects/yars/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[P3DTest.CopyConstructor]=]  /Volumes/Eregion/projects/yars/bin/yars_tests [==[--gtest_filter=P3DTest.CopyConstructor]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[P3DTest.CopyConstructor]=]  PROPERTIES WORKING_DIRECTORY /Volumes/Eregion/projects/yars/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[P3DTest.AdditionOperator]=]  /Volumes/Eregion/projects/yars/bin/yars_tests [==[--gtest_filter=P3DTest.AdditionOperator]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[P3DTest.AdditionOperator]=]  PROPERTIES WORKING_DIRECTORY /Volumes/Eregion/projects/yars/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[P3DTest.SubtractionOperator]=]  /Volumes/Eregion/projects/yars/bin/yars_tests [==[--gtest_filter=P3DTest.SubtractionOperator]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[P3DTest.SubtractionOperator]=]  PROPERTIES WORKING_DIRECTORY /Volumes/Eregion/projects/yars/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[P3DTest.ScalarMultiplication]=]  /Volumes/Eregion/projects/yars/bin/yars_tests [==[--gtest_filter=P3DTest.ScalarMultiplication]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[P3DTest.ScalarMultiplication]=]  PROPERTIES WORKING_DIRECTORY /Volumes/Eregion/projects/yars/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[P3DTest.EqualityOperator]=]  /Volumes/Eregion/projects/yars/bin/yars_tests [==[--gtest_filter=P3DTest.EqualityOperator]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[P3DTest.EqualityOperator]=]  PROPERTIES WORKING_DIRECTORY /Volumes/Eregion/projects/yars/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[P3DTest.Length]=]  /Volumes/Eregion/projects/yars/bin/yars_tests [==[--gtest_filter=P3DTest.Length]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[P3DTest.Length]=]  PROPERTIES WORKING_DIRECTORY /Volumes/Eregion/projects/yars/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[PoseTest.DefaultConstructor]=]  /Volumes/Eregion/projects/yars/bin/yars_tests [==[--gtest_filter=PoseTest.DefaultConstructor]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[PoseTest.DefaultConstructor]=]  PROPERTIES WORKING_DIRECTORY /Volumes/Eregion/projects/yars/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[PoseTest.EulerConstructor]=]  /Volumes/Eregion/projects/yars/bin/yars_tests [==[--gtest_filter=PoseTest.EulerConstructor]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[PoseTest.EulerConstructor]=]  PROPERTIES WORKING_DIRECTORY /Volumes/Eregion/projects/yars/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[PoseTest.QuaternionConstructor]=]  /Volumes/Eregion/projects/yars/bin/yars_tests [==[--gtest_filter=PoseTest.QuaternionConstructor]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[PoseTest.QuaternionConstructor]=]  PROPERTIES WORKING_DIRECTORY /Volumes/Eregion/projects/yars/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[PoseTest.CopyConstructor]=]  /Volumes/Eregion/projects/yars/bin/yars_tests [==[--gtest_filter=PoseTest.CopyConstructor]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[PoseTest.CopyConstructor]=]  PROPERTIES WORKING_DIRECTORY /Volumes/Eregion/projects/yars/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[PoseTest.AssignmentOperator]=]  /Volumes/Eregion/projects/yars/bin/yars_tests [==[--gtest_filter=PoseTest.AssignmentOperator]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[PoseTest.AssignmentOperator]=]  PROPERTIES WORKING_DIRECTORY /Volumes/Eregion/projects/yars/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[PoseTest.AngleConversion]=]  /Volumes/Eregion/projects/yars/bin/yars_tests [==[--gtest_filter=PoseTest.AngleConversion]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[PoseTest.AngleConversion]=]  PROPERTIES WORKING_DIRECTORY /Volumes/Eregion/projects/yars/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BraitenbergRegressionTest.BasicDataTypesWork]=]  /Volumes/Eregion/projects/yars/bin/yars_tests [==[--gtest_filter=BraitenbergRegressionTest.BasicDataTypesWork]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BraitenbergRegressionTest.BasicDataTypesWork]=]  PROPERTIES WORKING_DIRECTORY /Volumes/Eregion/projects/yars/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BraitenbergRegressionTest.ConfigurationFileExists]=]  /Volumes/Eregion/projects/yars/bin/yars_tests [==[--gtest_filter=BraitenbergRegressionTest.ConfigurationFileExists]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BraitenbergRegressionTest.ConfigurationFileExists]=]  PROPERTIES WORKING_DIRECTORY /Volumes/Eregion/projects/yars/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  yars_tests_TESTS P3DTest.DefaultConstructor P3DTest.ParameterizedConstructor P3DTest.CopyConstructor P3DTest.AdditionOperator P3DTest.SubtractionOperator P3DTest.ScalarMultiplication P3DTest.EqualityOperator P3DTest.Length PoseTest.DefaultConstructor PoseTest.EulerConstructor PoseTest.QuaternionConstructor PoseTest.CopyConstructor PoseTest.AssignmentOperator PoseTest.AngleConversion BraitenbergRegressionTest.BasicDataTypesWork BraitenbergRegressionTest.ConfigurationFileExists)
