
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/Users/zahedi/.local/bin/"
      - "/Users/zahedi/.bun/bin/"
      - "/opt/miniconda3/bin/"
      - "/opt/miniconda3/condabin/"
      - "/usr/local/opt/python@3.9/bin/"
      - "/usr/local/opt/openssl/bin/"
      - "/Volumes/Eregion/projects/yars/_deps/googletest-subbuild/"
      - "/usr/local/bin/"
      - "/usr/local/texlive/2014/bin/x86_64-darwin/"
      - "/Applications/Julia.app/Contents/Resources/julia/bin/"
      - "/Applications/MATLAB_R2015a.app/bin/"
      - "/usr/local/sbin/"
      - "/opt/homebrew/bin/"
      - "/opt/homebrew/sbin/"
      - "/System/Cryptexes/App/usr/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/"
      - "/Library/Apple/usr/bin/"
      - "/Applications/VMware Fusion.app/Contents/Public/"
      - "/Users/zahedi/.cargo/bin/"
      - "/Applications/iTerm.app/Contents/Resources/utilities/"
      - "/Users/zahedi/projects/go/bin/"
      - "/Users/zahedi/projects/3rd_party/sofa/v16.08/build/install/bin/"
      - "/Users/zahedi/Library/Python/2.7/bin/"
      - "/Users/zahedi/.cache/lm-studio/bin/"
      - "/Users/zahedi/.grit/bin/env/"
    searched_directories:
      - "/Users/zahedi/.local/bin/uname"
      - "/Users/zahedi/.bun/bin/uname"
      - "/opt/miniconda3/bin/uname"
      - "/opt/miniconda3/condabin/uname"
      - "/usr/local/opt/python@3.9/bin/uname"
      - "/usr/local/opt/openssl/bin/uname"
      - "/Volumes/Eregion/projects/yars/_deps/googletest-subbuild/uname"
      - "/usr/local/bin/uname"
      - "/usr/local/texlive/2014/bin/x86_64-darwin/uname"
      - "/Applications/Julia.app/Contents/Resources/julia/bin/uname"
      - "/Applications/MATLAB_R2015a.app/bin/uname"
      - "/usr/local/sbin/uname"
      - "/opt/homebrew/bin/uname"
      - "/opt/homebrew/sbin/uname"
      - "/System/Cryptexes/App/usr/bin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/Users/zahedi/.local/bin"
        - "/Users/zahedi/.local/bin"
        - "/Users/zahedi/.bun/bin"
        - "/opt/miniconda3/bin"
        - "/opt/miniconda3/bin"
        - "/opt/miniconda3/condabin"
        - "/usr/local/opt/python@3.9/bin"
        - "/usr/local/opt/openssl/bin"
        - "."
        - "/usr/local/bin"
        - "/usr/local/texlive/2014/bin/x86_64-darwin"
        - "/Applications/Julia.app/Contents/Resources/julia/bin"
        - "/Applications/MATLAB_R2015a.app/bin"
        - "/usr/local/sbin"
        - "/opt/homebrew/bin"
        - "/opt/homebrew/sbin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/Library/Apple/usr/bin"
        - "/Applications/VMware Fusion.app/Contents/Public"
        - "/Users/zahedi/.cargo/bin"
        - "/Applications/iTerm.app/Contents/Resources/utilities"
        - "/Users/zahedi/projects/go/bin"
        - "/Users/zahedi/projects/3rd_party/sofa/v16.08/build/install/bin"
        - "/Users/zahedi/Library/Python/2.7/bin"
        - "/Users/zahedi/.cache/lm-studio/bin"
        - "/Users/zahedi/.grit/bin/env"
        - "/Users/zahedi/.cache/lm-studio/bin"
        - "/Users/zahedi/.grit/bin/env"
  -
    kind: "message-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Darwin - 24.6.0 - arm64
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/Platform/Darwin.cmake:76 (find_program)"
      - "/opt/homebrew/share/cmake/Modules/CMakeSystemSpecificInformation.cmake:32 (include)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_INSTALL_NAME_TOOL"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "install_name_tool"
    candidate_directories:
      - "/Users/zahedi/.local/bin/"
      - "/Users/zahedi/.bun/bin/"
      - "/opt/miniconda3/bin/"
      - "/opt/miniconda3/condabin/"
      - "/usr/local/opt/python@3.9/bin/"
      - "/usr/local/opt/openssl/bin/"
      - "/Volumes/Eregion/projects/yars/_deps/googletest-subbuild/"
      - "/usr/local/bin/"
      - "/usr/local/texlive/2014/bin/x86_64-darwin/"
      - "/Applications/Julia.app/Contents/Resources/julia/bin/"
      - "/Applications/MATLAB_R2015a.app/bin/"
      - "/usr/local/sbin/"
      - "/opt/homebrew/bin/"
      - "/opt/homebrew/sbin/"
      - "/System/Cryptexes/App/usr/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/"
      - "/Library/Apple/usr/bin/"
      - "/Applications/VMware Fusion.app/Contents/Public/"
      - "/Users/zahedi/.cargo/bin/"
      - "/Applications/iTerm.app/Contents/Resources/utilities/"
      - "/Users/zahedi/projects/go/bin/"
      - "/Users/zahedi/projects/3rd_party/sofa/v16.08/build/install/bin/"
      - "/Users/zahedi/Library/Python/2.7/bin/"
      - "/Users/zahedi/.cache/lm-studio/bin/"
      - "/Users/zahedi/.grit/bin/env/"
    searched_directories:
      - "/Users/zahedi/.local/bin/install_name_tool"
      - "/Users/zahedi/.bun/bin/install_name_tool"
      - "/opt/miniconda3/bin/install_name_tool"
      - "/opt/miniconda3/condabin/install_name_tool"
      - "/usr/local/opt/python@3.9/bin/install_name_tool"
      - "/usr/local/opt/openssl/bin/install_name_tool"
      - "/Volumes/Eregion/projects/yars/_deps/googletest-subbuild/install_name_tool"
      - "/usr/local/bin/install_name_tool"
      - "/usr/local/texlive/2014/bin/x86_64-darwin/install_name_tool"
      - "/Applications/Julia.app/Contents/Resources/julia/bin/install_name_tool"
      - "/Applications/MATLAB_R2015a.app/bin/install_name_tool"
      - "/usr/local/sbin/install_name_tool"
      - "/opt/homebrew/bin/install_name_tool"
      - "/opt/homebrew/sbin/install_name_tool"
      - "/System/Cryptexes/App/usr/bin/install_name_tool"
    found: "/usr/bin/install_name_tool"
    search_context:
      ENV{PATH}:
        - "/Users/zahedi/.local/bin"
        - "/Users/zahedi/.local/bin"
        - "/Users/zahedi/.bun/bin"
        - "/opt/miniconda3/bin"
        - "/opt/miniconda3/bin"
        - "/opt/miniconda3/condabin"
        - "/usr/local/opt/python@3.9/bin"
        - "/usr/local/opt/openssl/bin"
        - "."
        - "/usr/local/bin"
        - "/usr/local/texlive/2014/bin/x86_64-darwin"
        - "/Applications/Julia.app/Contents/Resources/julia/bin"
        - "/Applications/MATLAB_R2015a.app/bin"
        - "/usr/local/sbin"
        - "/opt/homebrew/bin"
        - "/opt/homebrew/sbin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/Library/Apple/usr/bin"
        - "/Applications/VMware Fusion.app/Contents/Public"
        - "/Users/zahedi/.cargo/bin"
        - "/Applications/iTerm.app/Contents/Resources/utilities"
        - "/Users/zahedi/projects/go/bin"
        - "/Users/zahedi/projects/3rd_party/sofa/v16.08/build/install/bin"
        - "/Users/zahedi/Library/Python/2.7/bin"
        - "/Users/zahedi/.cache/lm-studio/bin"
        - "/Users/zahedi/.grit/bin/env"
        - "/Users/zahedi/.cache/lm-studio/bin"
        - "/Users/zahedi/.grit/bin/env"
      CMAKE_INSTALL_PREFIX: "/usr/local"
...
