#include "OgreHandler.h"
#include <yars/configuration/data/Data.h>
#include <yars/util/Directories.h>

#include <OGRE/Overlay/OgreOverlaySystem.h>
#include <OGRE/Overlay/OgreFontManager.h>

// RTSS Material Listener: generates shaders for materials without them
class RTSSMaterialListener : public Ogre::MaterialManager::Listener
{
public:
  RTSSMaterialListener(Ogre::RTShader::ShaderGenerator* sg) : _shaderGenerator(sg) {}

  Ogre::Technique* handleSchemeNotFound(unsigned short schemeIndex,
                                         const Ogre::String& schemeName,
                                         Ogre::Material* originalMaterial,
                                         unsigned short lodIndex,
                                         const Ogre::Renderable* rend) override
  {
    if (schemeName != Ogre::RTShader::ShaderGenerator::DEFAULT_SCHEME_NAME)
      return nullptr;

    // Attempt to create RTSS shader for this material
    bool success = _shaderGenerator->createShaderBasedTechnique(
        *originalMaterial,
        Ogre::MaterialManager::DEFAULT_SCHEME_NAME,
        schemeName);

    if (success)
    {
      // Find and return the generated technique
      for (auto tech : originalMaterial->getTechniques())
      {
        if (tech->getSchemeName() == schemeName)
          return tech;
      }
    }
    return nullptr;
  }

private:
  Ogre::RTShader::ShaderGenerator* _shaderGenerator;
};

static RTSSMaterialListener* gRTSSMaterialListener = nullptr;

OgreHandler *OgreHandler::_me = NULL;

OgreHandler *OgreHandler::instance()
{
  if (_me == NULL)
    _me = new OgreHandler();
  return _me;
}

void OgreHandler::shutdown()
{
  if (_me != NULL)
  {
    delete _me;
    _me = NULL;
  }
}

OgreHandler::~OgreHandler()
{
  // Clean up RTSS
  if (_shaderGenerator)
  {
    _shaderGenerator->removeSceneManager(_sceneManager);
    Ogre::RTShader::ShaderGenerator::destroy();
    _shaderGenerator = nullptr;
  }

  // Remove material listener
  if (gRTSSMaterialListener)
  {
    Ogre::MaterialManager::getSingleton().removeListener(gRTSSMaterialListener);
    delete gRTSSMaterialListener;
    gRTSSMaterialListener = nullptr;
  }

  // Clean up STBI codec
  Ogre::STBIImageCodec::shutdown();

  // Clean up scene graph
  if (_sceneGraph)
  {
    delete _sceneGraph;
    _sceneGraph = nullptr;
  }

  // Delete root (this cleans up scene manager, plugins, etc.)
  if (_root)
  {
    delete _root;
    _root = nullptr;
  }
}

OgreHandler::OgreHandler()
{
  Ogre::LogManager *lm = new Ogre::LogManager();
  lm->createLog("ogre.log", true, false, false); // create silent logging

#ifdef __APPLE__
  _root = new Ogre::Root("plugins.cfg", "", ""); // no log file created here (see 1 line above)
#else                                            // __APPLE__
  _root = new Ogre::Root("plugins.cfg", "ogre.cfg", ""); // no log file created here (see 1 line above)
#endif                                           // __APPLE__

  // Install plugins directly (framework static linking on macOS)
  _GL3PlusPlugin = new Ogre::GL3PlusPlugin();
  _root->installPlugin(_GL3PlusPlugin);

  _particlePlugin = new Ogre::ParticleFXPlugin();
  _root->installPlugin(_particlePlugin);

  // Initialize STBI codec for image loading (PNG, JPG, etc.)
  Ogre::STBIImageCodec::startup();

  if (_root->getAvailableRenderers().empty())
  {
    OGRE_EXCEPT(Ogre::Exception::ERR_INTERNAL_ERROR, "Failed to initialize RenderSystem_GL3Plus", "main");
  }
  _root->setRenderSystem(_root->getAvailableRenderers()[0]);
  _root->initialise(false);
  // OGRE 14: ST_GENERIC removed, use "DefaultSceneManager"
  _sceneManager = _root->createSceneManager("DefaultSceneManager", "YARS SceneManager");
}

void OgreHandler::setupSceneManager()
{
  Ogre::OverlaySystem *mOverlaySystem = new Ogre::OverlaySystem();
  _sceneManager->addRenderQueueListener(mOverlaySystem);

  // Initialize RTSS (Runtime Shader System) BEFORE loading resources
  // This allows RTSS to hook into the material manager for fixed-function emulation
  if (Ogre::RTShader::ShaderGenerator::initialize())
  {
    _shaderGenerator = Ogre::RTShader::ShaderGenerator::getSingletonPtr();
    _shaderGenerator->addSceneManager(_sceneManager);

    // Set shader cache path and target language
    _shaderGenerator->setTargetLanguage("glsl");

    // Add RTSS shader library to OgreInternal resource group (where RTSS looks for FFPLib)
    // Read path from rtss.cfg (generated by cmake)
    Ogre::ResourceGroupManager& rgm = Ogre::ResourceGroupManager::getSingleton();
    Ogre::String rtssPath;
    if (Directories::doesFileExist("rtss.cfg"))
    {
      Ogre::ConfigFile rtssConfig;
      rtssConfig.load("rtss.cfg");
      rtssPath = rtssConfig.getSetting("ShaderLibPath", "RTSS");
    }
    else
    {
      // Fallback: try relative path from build directory
      rtssPath = "../ext/ogre/Media/RTShaderLib";
    }
    rgm.addResourceLocation(rtssPath, "FileSystem", Ogre::ResourceGroupManager::INTERNAL_RESOURCE_GROUP_NAME);
    // Initialize OgreInternal resources for RTSS
    rgm.initialiseResourceGroup(Ogre::ResourceGroupManager::INTERNAL_RESOURCE_GROUP_NAME);

    // Register material listener to generate shaders on demand
    gRTSSMaterialListener = new RTSSMaterialListener(_shaderGenerator);
    Ogre::MaterialManager::getSingleton().addListener(gRTSSMaterialListener);

    // Set the scene manager to use RTSS shaders
    Ogre::MaterialManager::getSingleton().setActiveScheme(Ogre::RTShader::ShaderGenerator::DEFAULT_SCHEME_NAME);
  }

  // Load resources from resources.cfg (generated by cmake with absolute paths)
  Ogre::ResourceGroupManager& rgm = Ogre::ResourceGroupManager::getSingleton();

  if (Directories::doesFileExist("resources.cfg"))
  {
    Ogre::ConfigFile cf;
    cf.load("resources.cfg");
    for (const auto& section : cf.getSettingsBySection())
    {
      const Ogre::String& secName = section.first;
      for (const auto& setting : section.second)
      {
        const Ogre::String& typeName = setting.first;
        const Ogre::String& archName = setting.second;
        rgm.addResourceLocation(archName, typeName, secName);
      }
    }
  }
  else
  {
    OGRE_EXCEPT(Ogre::Exception::ERR_FILE_NOT_FOUND, "resources.cfg not found. Run from build directory.", "OgreHandler::setupSceneManager");
  }

  rgm.initialiseAllResourceGroups();

  // Generate RTSS shaders for all materials without shaders
  if (_shaderGenerator)
  {
    auto& matMgr = Ogre::MaterialManager::getSingleton();
    auto it = matMgr.getResourceIterator();
    while (it.hasMoreElements())
    {
      Ogre::ResourcePtr resPtr = it.getNext();
      Ogre::MaterialPtr mat = Ogre::static_pointer_cast<Ogre::Material>(resPtr);

      if (!mat->isLoaded())
        mat->load();

      // Skip materials that already have shaders
      if (!mat->getTechnique(0))
        continue;
      if (mat->getTechnique(0)->getPass(0)->hasGpuProgram(Ogre::GPT_VERTEX_PROGRAM))
        continue;

      _shaderGenerator->createShaderBasedTechnique(
          *mat,
          Ogre::MaterialManager::DEFAULT_SCHEME_NAME,
          Ogre::RTShader::ShaderGenerator::DEFAULT_SCHEME_NAME);
    }

    // Load fonts explicitly and apply custom font shaders for GL3Plus
    auto& fontMgr = Ogre::FontManager::getSingleton();
    auto fontIt = fontMgr.getResourceIterator();
    auto& gpuMgr = Ogre::GpuProgramManager::getSingleton();

    // Verify font shaders exist before applying
    bool haveFontShaders = gpuMgr.resourceExists("YARS/FontVP") &&
                           gpuMgr.resourceExists("YARS/FontFP");

    if (haveFontShaders)
    {
      while (fontIt.hasMoreElements())
      {
        Ogre::ResourcePtr fontRes = fontIt.getNext();
        Ogre::FontPtr font = Ogre::static_pointer_cast<Ogre::Font>(fontRes);

        if (!font->isLoaded())
          font->load();

        // Get font material and apply custom font shaders
        Ogre::MaterialPtr fontMat = font->getMaterial();
        if (fontMat && fontMat->getTechnique(0))
        {
          Ogre::Pass* pass = fontMat->getTechnique(0)->getPass(0);
          if (!pass->hasGpuProgram(Ogre::GPT_VERTEX_PROGRAM))
          {
            pass->setVertexProgram("YARS/FontVP");
            pass->setFragmentProgram("YARS/FontFP");
          }
        }
      }
    }
    else
    {
      Ogre::LogManager::getSingleton().logMessage(
        "YARS: Font shaders not found - overlay text may not render correctly");
    }
  }

  _sceneManager->setSkyDome(true, Data::instance()->current()->screens()->sky(), 20, 10);
  // _sceneManager->setSkyBox(true, "YARS/SkyBox", 100000.0);

  _sceneManager->setAmbientLight(Ogre::ColourValue(0.5, 0.5, 0.5));
  // OGRE 14: Lights must be attached to nodes, position is set on the node
  Ogre::SceneNode *lightNode = _sceneManager->getRootSceneNode()->createChildSceneNode("lightNode");
  lightNode->setPosition(75, 150, 75);
  Ogre::Light *lightSun = _sceneManager->createLight("sun");
  lightSun->setSpecularColour(0.25, 0.25, 0.25);
  lightNode->attachObject(lightSun);

  //lightSun->setType(Ogre::Light::LT_DIRECTIONAL);
  //lightSun->setPosition(25,25,100);
  //lightSun->setDiffuseColour(Ogre::ColourValue(0.8, 0.8, 0.8));
  //lightSun->setSpecularColour(1.0, 1.0, 1.0);
  //lightSun->setDirection(Ogre::Vector3(-1, -1, 0));

  // Ogre::Light* specularSun = _sceneManager->createLight("spec sun");
  // specularSun->setPosition(75,150,75);
  // specularSun->setDiffuseColour(0.0, 0.0, 0.0);
  // specularSun->setSpecularColour(0.5, 0.5, 0.5);
  // node->attachObject(specularSun);

  _rootNode = _sceneManager->getRootSceneNode()->createChildSceneNode();
  _sceneGraph = new SceneGraph(_rootNode, _sceneManager);

  // _textOverlay  = new TextOverlay("Legend Text Overlay");
  // Ogre::Real x = 10;
  // Ogre::Real y = 10;
  // _textOverlay->addTextBox("legend",
  // "^0YARS, Zahedi et al.", x, y, 150, 20,
  // Ogre::ColourValue(75.0/255.0, 117.0/255.0, 148.0/255.0,1.0f),
  // "Legend", "20");

  // #ifdef USE_SHADOW_MAPS
  // _sceneManager->setShadowTexturePixelFormat(Ogre::PF_FLOAT16_R);
  // _sceneManager->setShadowTechnique(Ogre::SHADOWTYPE_TEXTURE_ADDITIVE);
  // _sceneManager->setShadowTextureSelfShadow(true);
  // _sceneManager->setShadowTextureCasterMaterial("ShadowCaster");
  // _sceneManager->setShadowTextureReceiverMaterial("ShadowReceiver");
  // #else // USE_SHADOW_MAPS
  // OGRE 14: Shadows disabled - require custom shadow shaders for OGRE 14
  // TODO: Implement shader-based shadows (texture shadow mapping)
  _sceneManager->setShadowTechnique(Ogre::SHADOWTYPE_NONE);
  //#endif // USE_SHADOW_MAPS

  // _sceneManager->setShadowTextureSelfShadow(true);
  // _sceneManager->setShadowTextureCasterMaterial("DepthShadowmap/Caster/Float");
  // _sceneManager->setShadowTextureReceiverMaterial("Ogre/DepthShadowmap/Caster/Float");
  // _sceneManager->setShadowTexturePixelFormat(Ogre::PF_FLOAT32_R);
  // _sceneManager->setShadowCasterRenderBackFaces(false);
  // _sceneManager->setShadowTechnique(Ogre::SHADOWTYPE_TEXTURE_ADDITIVE_INTEGRATED);
}

Ogre::SceneManager *OgreHandler::getSceneManager()
{
  return _sceneManager;
}

void OgreHandler::reset()
{
  _sceneGraph->reset();
}

void OgreHandler::step()
{
  // cout << "OgreHandler 0" << endl;
  _sceneGraph->update();
  // cout << "OgreHandler 1" << endl;
  _root->renderOneFrame();
  // cout << "OgreHandler 2" << endl;
}

Ogre::Root *OgreHandler::root()
{
  return _root;
}
