if(UNIX)
  execute_process(COMMAND ${CMAKE_COMMAND} -E create_symlink ${CMAKE_SOURCE_DIR}/xml       ${CMAKE_BINARY_DIR}/xml)
  execute_process(COMMAND ${CMAKE_COMMAND} -E create_symlink ${CMAKE_SOURCE_DIR}/contrib/py  ${CMAKE_BINARY_DIR}/py)
  execute_process(COMMAND ${CMAKE_COMMAND} -E create_symlink ${CMAKE_SOURCE_DIR}/ply         ${CMAKE_BINARY_DIR}/ply)
  execute_process(COMMAND ${CMAKE_COMMAND} -E create_symlink ${CMAKE_SOURCE_DIR}/scripts     ${CMAKE_BINARY_DIR}/scripts)
  execute_process(COMMAND ${CMAKE_COMMAND} -E create_symlink ${CMAKE_SOURCE_DIR}/contrib/controller     ${CMAKE_BINARY_DIR}/controller)
  # Ogre resource directories needed at runtime (relative paths in OgreHandler.cpp)
  execute_process(COMMAND ${CMAKE_COMMAND} -E create_symlink ${CMAKE_SOURCE_DIR}/materials  ${CMAKE_BINARY_DIR}/materials)
  execute_process(COMMAND ${CMAKE_COMMAND} -E create_symlink ${CMAKE_SOURCE_DIR}/fonts      ${CMAKE_BINARY_DIR}/fonts)
  execute_process(COMMAND ${CMAKE_COMMAND} -E create_symlink ${CMAKE_SOURCE_DIR}/meshes     ${CMAKE_BINARY_DIR}/meshes)
  # RTShaderLib required for RTSS GLSL shader compilation
  execute_process(COMMAND ${CMAKE_COMMAND} -E make_directory ${CMAKE_BINARY_DIR}/ext/ogre)
  execute_process(COMMAND ${CMAKE_COMMAND} -E create_symlink ${CMAKE_SOURCE_DIR}/ext/ogre/RTShaderLib ${CMAKE_BINARY_DIR}/ext/ogre/RTShaderLib)
  # Ogre's Media/Main holds internal shadow textures (spot_shadow_fade.dds)
  # that SHADOWTYPE_TEXTURE_MODULATIVE requires from the OgreInternal group.
  execute_process(COMMAND ${CMAKE_COMMAND} -E make_directory ${CMAKE_BINARY_DIR}/ext/ogre/install/Media)
  execute_process(COMMAND ${CMAKE_COMMAND} -E create_symlink ${CMAKE_SOURCE_DIR}/ext/ogre/install/Media/Main ${CMAKE_BINARY_DIR}/ext/ogre/install/Media/Main)
endif(UNIX)
